name: Minecraft Brawl
main: org.infernogames.mb.MBPlugin
description: Super Smash Plugin
author: Ultimate
version: 0.0.4(dev)-b${BUILD_NUMBER}
website: http://mb.infernogames.org

commands:
   mb:
      description: The main Minecraft Brawl command
      usage: /<command> [args]
